### PR TITLE
New readability Anti-Pattern: Using CamelCase in function names

### PR DESCRIPTION
**Pull request by drgarcia1986**

### CODE REVIEW

**Comment by renanivo** [comment]
:+1:

**Comment by daniloakamine-luizalabs** [comment]
:+1:

**Comment by daniloakamine** [comment]
:+1:

**Comment by Ofborn** [comment]
:+1:

**Comment by eduardomartins-luizalabs** [comment]
:+1:

**Comment by pecota** [comment]
:+1:

**Comment by programmdesign** [comment]
@drgarcia1986. Thanks for your contribution.

**Comment by diegogarcia-luizalabs** [comment]
you're welcome :smile:

**Comment by drgarcia1986** [comment]
@programmdesign you're welcome :smile:

**Comment by programmdesign** [comment]
@drgarcia1986 @pecota @Ofborn @daniloakamine @renanivo: I'll also added an automated code check for it here: https://www.quantifiedcode.com/app/pattern/8cff95cc6b88440e872fe937a20ada87

**Comment by drgarcia1986** [comment]
Awesome :+1:

**Pull request merged**
